### ISSUE TITLE
download when archive already exists in dir

### ISSUE THREAD

**Issue by yoshuawuyts** [joehand/dat-js#15]
As per https://github.com/datproject/dat/issues/535, we probably want to download instead of throwing a warning when a dat already exists in a directory.

[`index.js:104`](https://github.com/joehand/dat-js/blob/master/index.js#L104) already has this marked as a TODO:
```js
    if (archive.key && !archive.owner) {
      // TODO: allow this but change to download
      return cb('Dat previously downloaded. Run dat ' + encoding.encode(archive.key) + ' to resume')
    }
```

Thanks!

**Comment by karissa** [comment]
this will get fixed in dat library as dat-js exposes more low level things
