### ISSUE TITLE
somebody write some quick start ?

### ISSUE THREAD

**Issue by nolotus** [joehand/dat-js#2]
dat just have cli(window error) desktop(error).
if i want write my app,how to with dat?
just api ,no detail document~

**Comment by juliangruber** [comment]
what errors are you getting with the cli and the desktop app?

**Comment by joehand** [comment]
Definitely! We've started to work on updated docs for the latest version of Dat. We have a [draft CLI quick start](https://github.com/datproject/docs/blob/update-content-toc/docs/dat-cli.md). If you are trying to build something with dat, I'd check out [this doc draft](https://github.com/datproject/docs/blob/update-content-toc/docs/diy-dat.md) too.

This module is still very early in development but we should have docs and a basic API up soon.
