### ISSUE TITLE
[discussion] dat-js requirements and design

### ISSUE THREAD

**Issue by yoshuawuyts** [joehand/dat-js#22]
# dat-js

Heya, I'm creating this issue to discuss the `dat-js` library API, because like
@karissa pointed out, if we should make changes to the `dat-js` library API,
now would be the right time. This is because currently only the API relies on
library, and there are plans being drafted to add the website, desktop app,
standalone http server and cluster too.

All text in this document is a best effort at consolidating my prior knowledge
of Dat with the conversations I've had with Karissa over the past few days
about Dat's internals. If anything in this document is off, I'd love to hear as
the goal is here to create common understanding about internals, problems,
goals and eventually agree on a solution. Here goes!
## What is a dat?

While we were talking about Dat, Karissa and I noticed we couldn't quite define
what a Dat is. Knowing what we define as "a Dat" is probably a good place to
start. This is the (paraphrased) definition we ended up with:

A Dat is a combination of data and a registry containing pointers to the data.
Usually this is **a directory containing a leveldb (registry) and files (data).**
The directory containing both of these is what we commonly refer to as "a dat".
But because "a dat" is a registry + data, other things can be "a dat" too.
Examples are:
- levelDB registry + S3 backend storing the files
- SLEEP archive containing both data + registry
## What do we want to do with a Dat?

When shaping the API, we probably want to cater to the common case first, and
then provide convenient escape hatches for the more specialized needs so it can
become the interface we base all our upstream consumers on without having to
fall back to using the lower level libs directly.

I think the common case is having a single directory containing both files as
the data, and a leveldb instance as the dat registry.

For the more advanced use cases it might make sense to instrument both
`hyperdrive` and `discovery-swarm` directly, providing upstream consumers with
direct access to limit the layers of abstraction we add with `dat-js`.
## So what would this look like?

``` js
const level = require('level')
const dat = require('dat-js')

// start a dat from some dir
dat('/path/to/my-dir', function (err, node) {
  if (err) throw err
  console.log('node is online')
  node.close()
})

// create a dat in the local dir
dat(process.cwd(), function (err, node) {
  if (err) throw err
  console.log('node is online')
  node.close()
})

// upload a dat from the local dir
dat({ some: 'option' }, function (err, node) {
  if (err) throw err

  node.share('somekey', function (err) {
    if (err) throw err
    node.close()
  })
})

// download a dat in the local dir
dat({ some: 'option' }, function (err, node) {
  if (err) throw err

  node.download('somekey', function (err) {
    if (err) throw err
    node.close()
  })
})

// download and upload a dat in the local dir
dat({ some: 'option' }, function (err, node) {
  if (err) throw err

  node.sync('somekey', function (err) {
    if (err) throw err
    node.close()
  })
})

// pass external db
const raf = require('random-access-file')
const db = level()
const opts = {
  hyperdrive: {
    db: db,
    file: (name) => raf('my-download-dir/' + name)
  }
}
dat(opts, function (err, node) {
  if (err) throw err

  node.download('somekey', function (err) {
    if (err) throw err
    node.close({ db: false }, function (err) {
      if (err) throw err
      db.close()
    })
  })
})
```
## Wrapping up

And that's all. I hope this proves to be a somewhat useful starting point to
start discussing the API. Feedback, suggestions and amendments are super
welcome! Thanks for your time, and looking forward to any comments you have!
:sparkles:

cc/ @joehand @juliangruber @karissa

**Comment by joehand** [comment]
In my mind `dat-js` should provide a common way for applications to create, access, resume, and seed (discover/upload/download) Dats. 

This enables one application to create a Dat, then other applications to read or share or update that Dat. For example, I create a Dat in the CLI. I should be able to add the folder containing that Dat to the desktop app without changing the key or re-adding the files. This is helpful in things like [dat-push](https://github.com/joehand/dat-push), where you want to just open an existing Dat and use the archive but not modify it.

At the root of it, I think that means we need to have a common expectation (as you define) for what is in the `.dat` folder and how you read it (I started [playing with that](https://github.com/joehand/dat-folder-db) this morning, but I still think it's tricky to abstract). This could mean the leveldb metadata + data files or SLEEP files + data files. But, most importantly, you need to be able to figure out what the existing key was so you can resume the archive (if there is only one key in a given hyperdrive we can get that, but otherwise we have to store it explicitly, as we are doing).

I think we are mostly in agreement there. Where I get caught up is the share, download, etc. especially when resuming Dats. Right now the file management, database management, and networking is all tightly coupled. That makes the API interface easy but means it's less useful in other applications.

**Comment by maxogden** [comment]
Great discussion topic! 

One thing worth mentioning for the purposes of API design is that in the near-to-mid-term future @mafintosh and I have discussed eliminating leveldb from our dependencies. We can replace leveldb with `sleep.dat` (https://github.com/datproject/docs/blob/master/docs/sleep.md#file-format). Only thing we need to do is, ya know, implement that and rewrite a buncha stuff to use it :D 

Having a flat file instead of leveldb will also make it easier to create full dats in the browser for downloading to the users machine, as well as dat implementations in other languages.

**Comment by joehand** [comment]
This morning we talked about prioritizing the ability to share & backup local folders with a live sync. Given that discussion, we can try to focus the API here for that use case.

There are a few distinct steps user go through in downloading a Dat: 

1. Initialize
2. Receive metadata
3. Download files
4. (_Later..._) Update metadata then update files

Right now we combine all those steps into a single command, "download". This is why the resume/sync idea gets confusing.

## Download Files from Dat link to local folder
1. Initialize Dat with *remote key*
2. Download Metadata
3. Download Latest Files
4. (_Later..._) Update Metadata + Files
  * Repeat 2-3 on command
  * Keep process open, live update metadata + files
5. (optional) Keep process open, re-seed Dat

### Comparing to `git`

For a thought exercise, I can see how our CLI download process could be similar to git:

```bash
$ dat clone e90efb1bcc491e0144ff804cc3e778fa3ea851443bee3d21883dd7f5cf1799bd dat_example

Dat downloaded to dat_example
```

This initializes a Dat and downloads  the latest metadata + files (Steps 1-3). This would exit after download is completed.

I can then check the status of my local folder:

```bash
$ cd dat_example && dat status

Your Dat is out-of-date with the source, your copy was last updated yesterday.
# (Maybe print out some info about metadata or dat.json here)
Use "dat fetch" to update.
```

```bash
$ cd dat_example && dat fetch

Dat updated with 19 new files.
```

**Comment by karissa** [comment]
Oh awesome, love the idea of a 'dat fetch' and 'dat clone' -- we can then have the 'dat sync' or just simply 'dat <folder>' that does two-way syncing.

**Comment by joehand** [comment]
I guess what I am getting at on the download side is:

1. Separate initialization (basically the current `dat.open()` function)
2. Separate syncing/downloading of metadata. This will allow things like downloading only specified files.
3. Make initializing/downloading new one separate from updating a Dat.

But I am still not sure how these overlap with sharing... =(

**Comment by karissa** [comment]
Hmm yes, it can be a hard thing to think about..

What I like is to think that sharing a new dat can be as simple as 
1) creating a new keypair
2) syncing changes on that keypair

**Comment by karissa** [comment]
It seems like there's a sync combination of keypair(metadata) + location(file content), that can be two-way or one-way (in either direction).

**Comment by joehand** [comment]
> It seems like there's a sync combination of keypair(metadata) + location(file content), that can be two-way or one-way (in either direction).

Ya, that makes sense! I think that is where I am getting caught up. As you are saying, on the share side, sync is:

1. Update file > Update metadata
2. Sync metadata

But on the download side it's:

1. Sync metadata
2. Update files

Does it make sense to make those the same command?

**Comment by karissa** [comment]
Things we will need in the desktop app from the api:
one writer

‘share a folder’ -> 
  1) create a link 
  2) joins a swarm 
  3) live sync the folder to the swarm

‘sync someone else’s folder’ ->
  1) joins the swarm for some link and keeps it up to date in a folder

‘pause syncing someone else's folder’ 
'stop uploading data' ->
  1) leave the swarm

'stop watching the folder'
  1) stop watching

‘see the history of a folder’ 
‘go back to a point in time’ ->
  1) keeping old versions around
  2) content-addressable store in .dat/history

**Comment by karissa** [comment]
here's another proposal
```js
var dat = Dat('/path/to/my/data', {
  file: function (name) {
    return somecustomthing(name)
  },
  db: memdb(),
  swarm: {
    utp: false,
    port: 1337
  }
}) // doesnt do anything except set options

dat.on('open', function () {
  // fired whenever an archive is created and opened with these options
  dat.owner
})

var archive = dat.sync({download: true, upload: true})
archive.on('open', function () {
  console.log('syncing')
})
archive.pause() // if in a swarm, will leave the swarm
archive.start()
archive.close() // will destroy the swarm object and database

// pass through the archive events
archive.on('upload')
archive.on('download')

var snapshot = dat.checkpoint({some: 'metadata'}, done)
function done (key) {
  console.log('seeding', key)
}

// pass through the archive events
snapshot.on('upload')
snapshot.on('download')
```

**Comment by yoshuawuyts** [comment]
Hmm, I feel I've got some concerns with an event emitter based API. I'll do my
best to enumerate them.

## error handling
For example I'm not seeing any error handling in the examples above; I feel
that `.on('error')` would probably be the most natural fit for use with event
emitters - and from the looks of it would be used in quite some places:
```js
var dat = Dat('/path/to/my/data')
dat.on('open', function () {
  dat.owner
})
dat.on('error', function (err) {
  console.error(err)
})
```

I feel streams has taught us that when error handling is optional people tend
to not handle errors. Instead I feel an errback API might help harden error
handling by making it non-optional (even `standard` will throw if the error is
not handled in this case):
```js
Dat('/path/to/my/data', function (err, dat) {
  if (err) console.error(err)
  dat.owner
})
```

## hidden methods
Something I tend to do when debugging programs is inspect returned objects.
Often the names of a returned value are telling:
```js
console.log(Object.keys(myObj)) // OR console.dir(myObj)
// => [ created, read, update, delete ]
```
When using event emitters this isn't possible anymore because it relies on
string matching. There's workarounds possible for sure, but I don't know of any
that are commonly used and therefor intuitive to people inspecting things.

## file size
Also finally: using event emitters in the browsers is reasonably heavy because
all Node core libs are heavy. There's always the option of hand rolling an
event emitter implementation though, but I feel it's not particularly ideal.
I'm not sure if this package was intended to be used in the browser, but I can
imagine that any sibling packages for browser use would have a similar API

---
Hope this was useful; API design is one of the topics I've got some experience
in and have formed opinions on, so hope I can be a bit of help here (:

**Comment by yoshuawuyts** [comment]
From IRC:
```txt
14:04:29 <@mafintosh> yoshuawuyts: https://github.com/joehand/dat-js/issues/22
14:04:51 <@mafintosh> not shipping event emitter is to the browser prob never gonna happen
14:05:02 <@mafintosh> its a dep *everywhere* more or less
14:08:26 <yoshuawuyts> mafintosh: yeah, that's fair - but that'd be related to the file size only, I still feel that other points like discoverability and error handling still apply
14:08:38 <@mafintosh> sure
```

**Comment by yoshuawuyts** [comment]
Hmm, I feel I've got some concerns with this API. I'll do my best to
enumerate
them.

## error handling
For example I'm not seeing any error handling in the examples above; I feel
that `.on('error')` would probably be the most natural fit for use with
event
emitters - and from the looks of it would be used in quite some places:
```js
var dat = Dat('/path/to/my/data')
dat.on('open', function () {
  dat.owner
})
dat.on('error', function (err) {
  console.error(err)
})
```

I feel streams has taught us that when error handling is optional people
tend
to not handle errors. Instead I feel an errback API might help harden error
handling by making it non-optional (even `standard` will throw if the error
is
not handled in this case):
```js
Dat('/path/to/my/data', function (err, dat) {
  if (err) console.error(err)
  dat.owner
})
```

## hidden methods
Something I tend to do when debugging programs is inspect returned objects.
Often the names of a returned value are telling:
```js
console.log(Object.keys(myObj)) // OR console.dir(myObj)
// => [ created, read, update, delete ]
```
When using event emitters this isn't possible anymore because it relies on
string matching. There's workarounds possible for sure, but I don't know of
any
that are commonly used and therefor intuitive to people inspecting things.

## file size
Also finally: using event emitters in the browsers is reasonably heavy
because
all Node core libs are heavy. There's always the option of hand rolling an
event emitter implementation though, but I feel it's not particularly ideal.
I'm not sure if this package was intended to be used in the browser, but I
can
imagine that any sibling packages for browser use would have a similar API

---
Hope this was useful; API design is one of the topics I've got some
experience
in and have formed opinions on, so hope I can be a bit of help here (:

**Comment by joehand** [comment]
It's worth taking a look at the [hyperdrive-import-files](https://github.com/juliangruber/hyperdrive-import-files) API. Julian did a great job with that making it event based if you want, but still has callbacks and standard error handling. 

That would let us collect events in one place (though that may be hectic) and have sub commands in another (after the callback). It's pretty close to what @yoshuawuyts proposed, just adding the emitter.

```js
var initDat = require('dat')

var status = initDat('new/dir/to/share', opts, function (err, dat) {
  // This function checks for a .dat folder, reads/creates the leveldb, then calls back
  if (err) throw err
  status.emit('open')

  if (dat.resume) {
    // There is a .dat folder in dir!
    if (dat.owner) return liveShare()
    else return dat.sync(done) // Download latest files
  }

  if (opts.link) dat.clone(done)
  else dat.createDat(dat.dir, liveShare) // This imports the files, could do other things later?

  function liveShare () {
    dat.watchDir() // Live watch files for changes
    dat.sync()
  }

  function done (err) {
    if (err) throw err
    dat.close()
    console.log('Dat up to date')
    process.exit(0)
  }
})

status.on('events!!!')
```

The main thing here is separating the event emitter from the main `dat` object. We could collect all the events from our models (importer, hyperdrive, swarms, etc.) and emit them to one emitter.

I think this design would work for multi-writer. `dat.sync()` would open network connections, share data to peers, and download changes. We'd have a separate function to write files (here its `dat.watchDir()`), allowing us to have different file watch + write options (live watch whole dir, track certain files, only update on command, etc.).

This would also allow us to do the git clone type functionality where we create the new directory based on the dat you are cloning:

```js
var status = initDat(opts, function (err, dat) {
  if (err) throw err
  if (typeof opts !== 'string' && opts.link) {
    // no directory, assume clone
   readDatJson(opts.link, function (err) {
     // read the dat.json and get dat name
     // create directory with name
     dat.clone(dirName)
   })
})
```

**Comment by karissa** [comment]
ok LGTM

**Comment by karissa** [comment]
Take a look at latest here: https://github.com/joehand/dat-js/pull/24

share and misc tests pass, now need to get download tests passing.

**Comment by karissa** [comment]
The problem i've found with the latest proposal is that its a bit difficult and confusing once you have two different objects related to the dat object -- one for events and the other for methods. Not sure if its necessary

**Comment by maxogden** [comment]
Closing discussion because ETOOLONG
